---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: roboshop
spec:
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80
          name: nginx-port
  nodeSelector:
    node: node-1