---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: roboshop
data:
  REDIS_HOST: "redis-service"
  CATALOGUE_HOST: "catalogue-service"
  CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: cart
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: cart
    spec:
      serviceAccountName: cart-service-account
      containers:
        - name: cart-cont
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.imagetag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: cart-port
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: cart-port
            failureThreshold: 2
            initialDelaySeconds: 50
            periodSeconds: 50
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: cart-port
            failureThreshold: 2
            initialDelaySeconds: 50
            periodSeconds: 50
            timeoutSeconds: 10
          envFrom:
            - configMapRef:
                name: cart-config

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    tier: backend
    component: cart
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: cart-port

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart-service-account
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
  