---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-storage
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: roboshop
data:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_VHOST: "/"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  serviceName: rabbitmq-headless-service
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  templates:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      serviceAccountName: rabbitmq-service-account
      containers:
        - name: rabbitmq-cont
          image: "{{ .Values.statefulset.image }}:{{ .Values.statefulset.imagetag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
              name: rabbitmq-port
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 5672
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          envFrom:
            - configMapRef:
                name: rabbitmq-config
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rabbitmq-storage
        resources:
          requests:
            storage: "5Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq-port

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless-service
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq-port

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-service-account
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    compnent: rabbitmq
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::257394454651:role/rabbitmq
  
  
